ublox_gps_node:
  ros__parameters:
    device: "/dev/ttyACM0"
    frame_id: "gps"
    baudrate: 115200
    # Disabling the "portable" model check that crashed it
    dynamic_model: "stationary"
    config_on_startup: false
    publish:
      all: true
