basekit_driver_node:
  ros__parameters:
    port: "/dev/ttyACM0"
    baudrate: 115200
    read_data:
      odom:
        type: "string"
      bms:
        type: "string"
      bumper:
        type: "string"
